[build]
  publish = "."
  command = ""

# Redirect form submissions (optional custom success page)
# [[redirects]]
#   from = "/"
#   to = "/?submitted=true"
#   status = 303

# Security headers (basic)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
