[build]
  publish = "."
  command = ""

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# (Optional) Add redirects or form success routes if needed
# [[redirects]]
#   from = "/"
#   to = "/?submitted=true"
#   status = 303
